config/routes.rb
Beersontap::Application.routes.draw do
  resources :beers
  get 'breweries/' => 'breweries#index'

end

app/models/beer.rb
class Beer
  include Mongoid::Document
  field :name, type: String
  field :type, type: String
  field :price, type: Float
  field :brewery, type: String
  field :ABV, type: Float
end

app/models/brewery.rb
class Brewery
  include Mongoid::Document
  field :name, type: String
  field :city, type: String
  field :founded, type: Integer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :set_beer, only: [:show, :edit, :update, :destroy]

  # GET /beers
  # GET /beers.json
  def index
    @beers = Beer.all
  end

  # GET /beers/1
  # GET /beers/1.json
  def show
  end

  # GET /beers/new
  def new
    @beer = Beer.new
  end

  # GET /beers/1/edit
  def edit
  end

  # POST /beers
  # POST /beers.json
  def create
    @beer = Beer.new(beer_params)

    respond_to do |format|
      if @beer.save
        format.html { redirect_to @beer, notice: 'Beer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @beer }
      else
        format.html { render action: 'new' }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beers/1
  # PATCH/PUT /beers/1.json
  def update
    respond_to do |format|
      if @beer.update(beer_params)
        format.html { redirect_to @beer, notice: 'Beer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beers/1
  # DELETE /beers/1.json
  def destroy
    @beer.destroy
    respond_to do |format|
      format.html { redirect_to beers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer
      @beer = Beer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_params
      params.require(:beer).permit(:name, :type, :price, :brewery, :ABV)
    end
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController

	def index
		@breweries = Brewery.all
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/beers/_form.html.erb
<%= form_for(@beer) do |f| %>
  <% if @beer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer.errors.count, "error") %> prohibited this beer from being saved:</h2>

      <ul>
      <% @beer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :brewery %><br>
    <%= f.text_field :brewery %>
  </div>
  <div class="field">
    <%= f.label :ABV %><br>
    <%= f.text_field :ABV %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beers/edit.html.erb
<h1>Editing beer</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer %> |
<%= link_to 'Back', beers_path %>

app/views/beers/index.html.erb
<h1>Listing beers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Price</th>
      <th>Brewery</th>
      <th>Abv</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @beers.each do |beer| %>
      <tr>
        <td><%= beer.name %></td>
        <td><%= beer.type %></td>
        <td><%= beer.price %></td>
        <td><%= beer.brewery %></td>
        <td><%= beer.ABV %></td>
        <td><%= link_to 'Show', beer %></td>
        <td><%= link_to 'Edit', edit_beer_path(beer) %></td>
        <td><%= link_to 'Destroy', beer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beer', new_beer_path %>

app/views/beers/new.html.erb
<h1>New beer</h1>

<%= render 'form' %>

<%= link_to 'Back', beers_path %>

app/views/beers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @beer.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @beer.type %>
</p>

<p>
  <strong>Price:</strong>
  <%= @beer.price %>
</p>

<p>
  <strong>Brewery:</strong>
  <%= @beer.brewery %>
</p>

<p>
  <strong>Abv:</strong>
  <%= @beer.ABV %>
</p>

<%= link_to 'Edit', edit_beer_path(@beer) %> |
<%= link_to 'Back', beers_path %>

app/views/breweries/index.html.erb
<h1>Hi, I'm a list of awesome breweries!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Beersontap</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>